### ISSUE TITLE
Torch_audioset is not compatible with latest pytorch version (1.9.0)

### ISSUE THREAD

**Issue by guillaume-orikio** [w-hc/torch_audioset#6]
With latest Pytorch version:
######## CONFIG ################
cffi==1.14.6
cycler==0.10.0
kiwisolver==1.3.1
matplotlib==3.4.2
numpy==1.21.1
Pillow==8.3.1
pycparser==2.20
pyparsing==2.4.7
python-dateutil==2.8.2
PyYAML==5.4.1
six==1.16.0
SoundFile==0.10.3.post1
torch==1.9.0
torchaudio==0.9.0
typing-extensions==3.10.0.0
##################################
Running:
python visualization.py /path/to/a/sound.wav 
It throws:
#####################################
Traceback (most recent call last):
  File "visualization.py", line 34, in <module>
    pt_model = torch_yamnet(pretrained=False)
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 167, in yamnet
    model = YAMNet()
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 139, in __init__
    self.add_module(name, layer_mod(kernel, stride, input_dim, output_dim))
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 79, in __init__
    Conv2d_tf(
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/home/guillaume/torch_audioset/.venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 430, in __init__
    super(Conv2d, self).__init__(
  File "/home/guillaume/torch_audioset/.venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 90, in __init__
    raise ValueError(
ValueError: Invalid padding string 'SAME', should be one of {'valid', 'same'}
#######################################

Then, when I replace "SAME" by "same" in file torch_audioset/yamnet/model.py
It throws:
##################################
Traceback (most recent call last):
  File "visualization.py", line 34, in <module>
    pt_model = torch_yamnet(pretrained=False)
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 167, in yamnet
    model = YAMNet()
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 139, in __init__
    self.add_module(name, layer_mod(kernel, stride, input_dim, output_dim))
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 79, in __init__
    Conv2d_tf(
  File "/home/guillaume/torch_audioset/torch_audioset/yamnet/model.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/home/guillaume/torch_audioset/.venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 430, in __init__
    super(Conv2d, self).__init__(
  File "/home/guillaume/torch_audioset/.venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 94, in __init__
    raise ValueError("padding='same' is not supported for strided convolutions")
ValueError: padding='same' is not supported for strided convolutions
###################################

Then, I don't know what to do :/

**Comment by guillaume-orikio** [comment]
https://pytorch.org/blog/pytorch-1.9-released/
https://github.com/pytorch/pytorch/pull/45667
Looks like that's not a simple font case deprecation, because they state they added "same" padding for non strided convolutions. Their new feature seems to partially doing what Conv2d_tf does, but generate a conflict when stride>1

May we just remove Conv2d_tf module, and use option padding="same", when version>=1.9.0, but it won't works for strided convolutions

**Comment by Guillaume-oso** [comment]
Nasty fix:
in torch_audioset/yamnet/model.py
######################
class Conv2d_tf(nn.Conv2d):
    """
    Conv2d with the padding behavior from TF Slim
    """
    def __init__(self, *args, **kwargs):
        padding = kwargs.pop("padding")
        super().__init__(*args, **kwargs)
        self.padding = padding
        assert self.padding == "SAME"
######################
It prevent the new conflict due to 1.9.0 pytorch version which now accept string type for padding argument.
